name: 'Setup rust corset'
description: 'Install rust and rust corset'

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install Corset
      shell: bash
      run: RUSTFLAGS=-Awarnings cargo install --git ssh://git@github.com/ConsenSys/corset --tag v9.7.15 --locked --force
